spring:
  profiles:
    active: dev
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
      
logging:
  level:
    com.angel: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    
angel:
  collectors:
    mock-mode: true
  cache:
    ttl:
      news: 300
      weather: 180
      recipes: 600
      stories: 1800
