server:
  port: 9090  # Port pour production (différent du dev)

spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres-service:5432/angeldb}
    username: ${DB_USERNAME:angel}
    password: ${DB_PASSWORD:changeme123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
      
logging:
  level:
    root: WARN
    com.angel: INFO
  pattern:
    console: '{"timestamp":"%d","level":"%level","logger":"%logger","message":"%msg"}%n'
    
angel:
  collectors:
    mock-mode: false
  performance:
    thread-pool:
      core-size: 20
      max-size: 100
  cache:
    redis:
      cluster:
        enabled: true
