server:
  port: 0  # Port aléatoire pour les tests

spring:
  config:
    activate:
      on-profile: test
    
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  
  flyway:
    enabled: false  # Désactivé pour les tests, on utilise create-drop
    
  redis:
    host: redis
    port: 6379
    
angel:
  collectors:
    enabled: false
  cache:
    redis:
      enabled: false
