apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: angel-update-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: angeldb
        - name: POSTGRES_USER
          value: angel
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: angel-update-secrets
              key: db-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-script
        configMap:
          name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: angel-update-dev
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
